In [1]:
1+1

2

In [2]:
    dic = {"key1": "v1", "key2": "v2", 3: 4}

In [3]:
dic

{'key1': 'v1', 'key2': 'v2', 3: 4}

In [4]:
dic.keys()

dict_keys(['key1', 'key2', 3])

In [5]:
print(list(dic.keys()))

['key1', 'key2', 3]


In [6]:
dic.values()

dict_values(['v1', 'v2', 4])

In [7]:
dic.items()

dict_items([('key1', 'v1'), ('key2', 'v2'), (3, 4)])

In [8]:
b = list(dic.items())

In [9]:
type(b)

list

In [10]:
dic['key1']

'v1'

In [11]:
dic.update({'test':'test1'})

In [12]:
dic

{'key1': 'v1', 'key2': 'v2', 3: 4, 'test': 'test1'}

In [13]:
dic.update({'key1':'test1'})

In [14]:
dic

{'key1': 'test1', 'key2': 'v2', 3: 4, 'test': 'test1'}

In [15]:
dic2 = {"key": 1, 'key':2}

In [16]:
dic2

{'key': 2}

In [17]:
1 in dic2

False

In [18]:
'key2' in dic

True

In [19]:
2 in dic2.values()

True

In [20]:
import numpy as np

In [21]:
data1 = [0,1,2,3,4,5]

In [22]:
a1 = np.array(data1)

In [23]:
a1

array([0, 1, 2, 3, 4, 5])

In [24]:
type(a1)

numpy.ndarray

In [25]:
a1.dtype

dtype('int32')

In [26]:
data2 = ['aas', 'd']
a1 = np.array(data2)
a1.dtype

dtype('<U3')

In [27]:
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [28]:
a2 = np.linspace(0,10,)
a2

array([ 0.        ,  0.20408163,  0.40816327,  0.6122449 ,  0.81632653,
        1.02040816,  1.2244898 ,  1.42857143,  1.63265306,  1.83673469,
        2.04081633,  2.24489796,  2.44897959,  2.65306122,  2.85714286,
        3.06122449,  3.26530612,  3.46938776,  3.67346939,  3.87755102,
        4.08163265,  4.28571429,  4.48979592,  4.69387755,  4.89795918,
        5.10204082,  5.30612245,  5.51020408,  5.71428571,  5.91836735,
        6.12244898,  6.32653061,  6.53061224,  6.73469388,  6.93877551,
        7.14285714,  7.34693878,  7.55102041,  7.75510204,  7.95918367,
        8.16326531,  8.36734694,  8.57142857,  8.7755102 ,  8.97959184,
        9.18367347,  9.3877551 ,  9.59183673,  9.79591837, 10.        ])

In [29]:
a2[1]

0.20408163265306123

In [30]:
a2.dtype

dtype('float64')

In [31]:
a2.astype(int)

array([ 0,  0,  0,  0,  0,  1,  1,  1,  1,  1,  2,  2,  2,  2,  2,  3,  3,
        3,  3,  3,  4,  4,  4,  4,  4,  5,  5,  5,  5,  5,  6,  6,  6,  6,
        6,  7,  7,  7,  7,  7,  8,  8,  8,  8,  8,  9,  9,  9,  9, 10])

In [32]:
np.random.rand(2,3)

array([[0.2345149 , 0.30266554, 0.24162078],
       [0.51945855, 0.27587853, 0.91274059]])

In [33]:
np.random.randint(1,3,4)

array([1, 2, 2, 1])

In [34]:
a3 = np.arange(5)
a3

array([0, 1, 2, 3, 4])

In [35]:
a3.sum()

10

In [36]:
a3.mean()

2.0

In [37]:
a3.cumsum()

array([ 0,  1,  3,  6, 10], dtype=int32)

In [38]:
a3.cumprod()

array([0, 0, 0, 0, 0], dtype=int32)

In [39]:
a3

array([0, 1, 2, 3, 4])

In [40]:
a1

array(['aas', 'd'], dtype='<U3')

In [41]:
data1

[0, 1, 2, 3, 4, 5]

In [43]:
a4 = np.array(data1)

In [44]:
a4

array([0, 1, 2, 3, 4, 5])

In [58]:
a5 = a4.reshape(3,2)

In [47]:
a4[0]

0

In [48]:
a4[1]

1

In [49]:
a4[2]

2

In [50]:
a4[5]

5

In [63]:
a5[2,1]

5

In [66]:
a5[2]

array([4, 5])

In [67]:
a5[a5>2]

array([3, 4, 5])

In [68]:
a = [1,2,3,4,5,6,7]

In [70]:
a[2]

3

In [71]:
a5[:,1]

array([1, 3, 5])

In [72]:
a5

array([[0, 1],
       [2, 3],
       [4, 5]])

In [73]:
a5[1, :]

array([2, 3])

In [75]:
from pandas import Series, DataFrame
import pandas as pd

In [76]:
s1 = Series([1,2,3,4])

In [77]:
s1

0    1
1    2
2    3
3    4
dtype: int64

In [78]:
date = pd.date_range(start='2019-12-26', end='2019-12-30')

In [79]:
date

DatetimeIndex(['2019-12-26', '2019-12-27', '2019-12-28', '2019-12-29',
               '2019-12-30'],
              dtype='datetime64[ns]', freq='D')

In [88]:
s=" \n qwe"

In [89]:
s

' \n qwe'

In [93]:
# 1. 다음 튜플을 리스트로 변환해라
a_1 = (1,2,3,4)
list(a_1)

[1, 2, 3, 4]

In [96]:
# 2. 다음을 튜플로 변환하세요
job = 'Data Scientist'
job_t = tuple(job)

In [98]:
# 3. 다음을 집합으로 변환하세요
job_s = set(job_t)

In [94]:
# 4. 다음 문자열을 슬라이싱 하여 cde만 출력해라
a_2 = "abcdefghijklmnopqrstuvwxyz"
a_2[2:5]

'cde'

In [100]:
# 5. 다음 항목을 딕셔너리로 만드세요
dic_1 = {"Venti": 9000, "Grande": 7000, "Tall": 3000}
dic_1

{'Venti': 9000, 'Grande': 7000, 'Tall': 3000}

In [101]:
# 6. 위에 딕셔너리에 short 2500을 추가해라
dic_1.update({"short": 2500})
dic_1

{'Venti': 9000, 'Grande': 7000, 'Tall': 3000, 'short': 2500}

In [103]:
#7. 키만 출력
dic_1.keys()

dict_keys(['Venti', 'Grande', 'Tall', 'short'])

In [104]:
#8. 값만 출력
dic_1.values()

dict_values([9000, 7000, 3000, 2500])

In [105]:
#9. 둘다 출력
dic_1.items()

dict_items([('Venti', 9000), ('Grande', 7000), ('Tall', 3000), ('short', 2500)])

In [111]:
# 다음리스트에서 애플만 지우기
list_a = ["Strawberry", "Apple", "Orange"]
print("삭제전: ", list_a)
list_a.remove("Apple")
print("삭제후: ", list_a)

삭제전:  ['Strawberry', 'Apple', 'Orange']
삭제후:  ['Strawberry', 'Orange']


In [112]:
# 90점이상 학점 A 는 패스 그외는 fail
score = [90, 80, 70, 100, 60]

for i in score:
    if i >= 90:
        print('pass')
    else:
        print('fail')

    

pass
fail
fail
pass
fail


In [113]:
# 5글자 이상 단어만 출력하기
q4 = ["nice", "study", "python", "anaconda", "!"]

for i in q4:
    if len(i) >= 5:
        print(i)

study
python
anaconda


In [168]:
# 다음 3개 숫자중 가장 큰수를 출력하세요
list_3 = [12, 6, 18]
max(list_3)


TypeError: 'int' object is not callable

In [173]:
#list_3 = [12, 6, 18]


AttributeError: 'list' object has no attribute 'max'

In [125]:
list_3 = [12, 6, 18]
max1 = 0
for i in list_3:
    if max1 < i:
        max1 = i
print(max1)

18


In [167]:
# 소문자는 대문자로 대문자는 소문자로 출력
str_1 = 'sfdTE'
list_5=[]
for i in str_1:
    if i.islower() == True:
        list_5.append(i.upper())
    else:
        list_5.append(i.lower())
rlt = "".join(list_5)
rlt

'SFDte'

In [162]:
for i in range(1,10):
    for j in range(2,10):
        print("{0} * {1} = {2}".format(j,i,i*j), end='\t')
    print()

2 * 1 = 2	3 * 1 = 3	4 * 1 = 4	5 * 1 = 5	6 * 1 = 6	7 * 1 = 7	8 * 1 = 8	9 * 1 = 9	
2 * 2 = 4	3 * 2 = 6	4 * 2 = 8	5 * 2 = 10	6 * 2 = 12	7 * 2 = 14	8 * 2 = 16	9 * 2 = 18	
2 * 3 = 6	3 * 3 = 9	4 * 3 = 12	5 * 3 = 15	6 * 3 = 18	7 * 3 = 21	8 * 3 = 24	9 * 3 = 27	
2 * 4 = 8	3 * 4 = 12	4 * 4 = 16	5 * 4 = 20	6 * 4 = 24	7 * 4 = 28	8 * 4 = 32	9 * 4 = 36	
2 * 5 = 10	3 * 5 = 15	4 * 5 = 20	5 * 5 = 25	6 * 5 = 30	7 * 5 = 35	8 * 5 = 40	9 * 5 = 45	
2 * 6 = 12	3 * 6 = 18	4 * 6 = 24	5 * 6 = 30	6 * 6 = 36	7 * 6 = 42	8 * 6 = 48	9 * 6 = 54	
2 * 7 = 14	3 * 7 = 21	4 * 7 = 28	5 * 7 = 35	6 * 7 = 42	7 * 7 = 49	8 * 7 = 56	9 * 7 = 63	
2 * 8 = 16	3 * 8 = 24	4 * 8 = 32	5 * 8 = 40	6 * 8 = 48	7 * 8 = 56	8 * 8 = 64	9 * 8 = 72	
2 * 9 = 18	3 * 9 = 27	4 * 9 = 36	5 * 9 = 45	6 * 9 = 54	7 * 9 = 63	8 * 9 = 72	9 * 9 = 81	


In [143]:
sum = 0
for i in range(1,1001):
    sum += i
print(sum)

500500


In [1]:
import numpy as np

In [2]:
np.random.randint(1,100, size=(5))

array([39,  7, 72, 81, 41])

In [3]:
np.random.seed(23)
np.random.randn(3,4)

array([[ 0.66698806,  0.02581308, -0.77761941,  0.94863382],
       [ 0.70167179, -1.05108156, -0.36754812, -1.13745969],
       [-1.32214752,  1.77225828, -0.34745899,  0.67014016]])

choice :주어진 1차원에서 ndarray 랜덤 샘플링

In [4]:
np.random.choice(100, size=(3,4))

array([[79, 90, 62, 57],
       [19, 33, 59, 39],
       [15, 36, 65,  1]])

In [8]:
x=np.arange(10)
np.random.choice(x, size = (2,2), replace=False)

array([[8, 0],
       [1, 5]])

In [17]:
np.arange(54).reshape(2,9,3)

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8],
        [ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17],
        [18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]],

       [[27, 28, 29],
        [30, 31, 32],
        [33, 34, 35],
        [36, 37, 38],
        [39, 40, 41],
        [42, 43, 44],
        [45, 46, 47],
        [48, 49, 50],
        [51, 52, 53]]])

In [19]:
a = np.array([1,2,3,4])

In [20]:
a

array([1, 2, 3, 4])

In [21]:
a2 = np.array((1,2,3,4))

In [22]:
a2 

array([1, 2, 3, 4])

In [23]:
import pandas as pd

In [24]:
data = {'state':['ohio','ohio','ohio','nevada','nevada'],
       'year':[2000,2001,2002,2001,2002],
       'pop':[1.5,1.7,3.6,2.4,2.9]}

In [25]:
data

{'state': ['ohio', 'ohio', 'ohio', 'nevada', 'nevada'],
 'year': [2000, 2001, 2002, 2001, 2002],
 'pop': [1.5, 1.7, 3.6, 2.4, 2.9]}

In [27]:
df=pd.DataFrame(data)

In [28]:
df

state  year  pop
0    ohio  2000  1.5
1    ohio  2001  1.7
2    ohio  2002  3.6
3  nevada  2001  2.4
4  nevada  2002  2.9

In [30]:
df[1:2]

state  year  pop
1  ohio  2001  1.7

In [31]:
df.loc[2]

state    ohio
year     2002
pop       3.6
Name: 2, dtype: object

In [32]:
df.iloc[2]

state    ohio
year     2002
pop       3.6
Name: 2, dtype: object

In [33]:
df['state']

0      ohio
1      ohio
2      ohio
3    nevada
4    nevada
Name: state, dtype: object

In [37]:
df.year

0    2000
1    2001
2    2002
3    2001
4    2002
Name: year, dtype: int64

In [38]:
df['state'][1:3]

1    ohio
2    ohio
Name: state, dtype: object

In [39]:
df.T

0     1     2       3       4
state  ohio  ohio  ohio  nevada  nevada
year   2000  2001  2002    2001    2002
pop     1.5   1.7   3.6     2.4     2.9

In [41]:
df.append(df, ignore_index=True)

state  year  pop
0    ohio  2000  1.5
1    ohio  2001  1.7
2    ohio  2002  3.6
3  nevada  2001  2.4
4  nevada  2002  2.9
5    ohio  2000  1.5
6    ohio  2001  1.7
7    ohio  2002  3.6
8  nevada  2001  2.4
9  nevada  2002  2.9

In [45]:
data = {'state2':['ohio','ohio','ohio','nevada','nevada'],
       'year2':[2000,2001,2002,2001,2002],
       'pop2':[1.5,1.7,3.6,2.4,2.9]}
df2 = pd.DataFrame(data)

In [46]:
df.join(df2)

state  year  pop  state2  year2  pop2
0    ohio  2000  1.5    ohio   2000   1.5
1    ohio  2001  1.7    ohio   2001   1.7
2    ohio  2002  3.6    ohio   2002   3.6
3  nevada  2001  2.4  nevada   2001   2.4
4  nevada  2002  2.9  nevada   2002   2.9

In [48]:
df.merge(df)

state  year  pop
0    ohio  2000  1.5
1    ohio  2001  1.7
2    ohio  2002  3.6
3  nevada  2001  2.4
4  nevada  2002  2.9

In [49]:
df.merge(df, on='state')

state  year_x  pop_x  year_y  pop_y
0     ohio    2000    1.5    2000    1.5
1     ohio    2000    1.5    2001    1.7
2     ohio    2000    1.5    2002    3.6
3     ohio    2001    1.7    2000    1.5
4     ohio    2001    1.7    2001    1.7
5     ohio    2001    1.7    2002    3.6
6     ohio    2002    3.6    2000    1.5
7     ohio    2002    3.6    2001    1.7
8     ohio    2002    3.6    2002    3.6
9   nevada    2001    2.4    2001    2.4
10  nevada    2001    2.4    2002    2.9
11  nevada    2002    2.9    2001    2.4
12  nevada    2002    2.9    2002    2.9